### ISSUE TITLE
Pull-to-refresh in Announcements controller

### ISSUE THREAD

**Issue by chriszielinski** [calblueprint/sage-mobile#286]
Announcements controller occasionally throws fatal error (index out of range) on pull-to-refresh

**Comment by amillman** [comment]
oh yea shit im probably gonna remove this....i think it has to do with the pagination

**Comment by chriszielinski** [comment]
I already got it. Haven't pushed any commits yet. Going to sleep for a little bit now. But what caused it was emptying the array of announcements before making the request for new ones, which gave the table view enough ms to 💀
